use_frameworks!
platform :ios, '11.0'

target 'WebViewConsole_Example' do
  pod 'WebViewConsole', path: '../'
  pod 'WebViewConsoleView', path: '../'

  target 'WebViewConsole_Tests' do
    inherit! :search_paths
  end
end
