use_frameworks!

target 'WebViewConsole_Example' do
  pod 'WebViewConsole', :path => '../'

  target 'WebViewConsole_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
